### ISSUE TITLE
Heya

### ISSUE THREAD

**Issue by ItsCEED** [ianlucas/cs2-match-plugin#1]
Im following the development of the plugin since you created the repo.

When we are going to see documentation and what are the future plans for it as i can see you are actively developing this one

**Comment by ianlucas** [comment]
Currently I'm in the process of testing the plugin, so the documentation (ConVars and commands namely) will be provided as soon as I feel we reached a stable state. I'll probably deleting all the releases and restart at v1 as I did with Inventory Simulator at that point.

Currently it's pretty usable for scrims, but I'm still testing the match system, and will be reworking some logic now that the core is working well.
